### ISSUE TITLE
Some test cases failure observed on sonic-buildimage master branch

### ISSUE THREAD

**Issue by w1nda** [sonic-net/sonic-mgmt#12490] opened 2024-04-17 14:07 UTC
**Description**

I notice that two test cases keep failing which are introduced by PR #12387
The first one is route/test_duplicate_route.py::test_duplicate_routes and the second one is gnmi/test_gnmi_configdb.py::test_gnmi_configdb_full_01.

**Steps to reproduce the issue:**
Just trigger the validation pipeline on sonic-buildimage master branch, then the validation will fail on kvmtest-t0 

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by yejianquan** [comment] 2024-04-17 14:19
Fixed with https://github.com/sonic-net/sonic-mgmt/pull/12485

**Comment by w1nda** [comment] 2024-04-17 14:29
> Fixed with #12485

The #12485 only fixed the failure on test_duplicate_route.py
However, there is still a failure on test_gnmi_configdb.py
Besides, the pipeline always exits on failure and cancels all tests that **didn't finish**, there are potential failures.

**Comment by w1nda** [comment] 2024-04-18 03:05
The root cause is #12387 was not blocked by test.
We need to improve it by getting test cases from source branch instead of master at mgmt side.

**Comment by w1nda** [comment] 2024-04-18 03:11
> The root cause is #12387 was not blocked by test. We need to improve it by getting test cases from source branch instead of master at mgmt side.

Hi @wangxin, is this improvement helpful?

**Comment by yutongzhang-microsoft** [comment] 2024-04-18 03:36
Hi, @w1nda, I don't think #12387 is the root cause. I have tested these new added cases for more than ten times, and they all passed. Can you check the image first?

**Comment by yutongzhang-microsoft** [comment] 2024-04-18 03:41
Hi, @w1nda, I will check the case test_gnmi_configdb.py

**Comment by w1nda** [comment] 2024-04-18 03:56
> Hi, @w1nda, I will check the case test_gnmi_configdb.py

Hi @yutongzhang-microsoft ,I believe you are not the author of the test case, so it's not proper to ask you fix the test case.

The problem is we have the chance to block #12387 while we didn't.

To prevent such issue, we need to improve it by getting test cases from source branch instead of master at mgmt side.

**Comment by yutongzhang-microsoft** [comment] 2024-04-18 05:42
Hi, @w1nda , I have checked the case test_gnmi_configdb.py. It can be successfully ran in PR test. Please check image first.

**Comment by yutongzhang-microsoft** [comment] 2024-04-18 05:57
This failure may caused by PR https://github.com/sonic-net/sonic-buildimage/pull/16957

**Comment by yutongzhang-microsoft** [comment] 2024-04-18 06:07
Temporarily remove the cases under folder `gnmi` #12499

**Closed by yutongzhang-microsoft** 2024-04-18 06:07 UTC
