### ISSUE TITLE
test_techsupport[acl-str-marvell-acs-1] and test_techsupport[mirroring-str-marvell-acs-1] test cases are failing because  sai_sdk_dump folder is not present in dump file

### ISSUE THREAD

**Issue by rajneeshaec** [sonic-net/sonic-mgmt#7520] opened 2023-02-20 10:39 UTC
**Description**
test_techsupport[acl-str-marvell-acs-1] and test_techsupport[mirroring-str-marvell-acs-1] test cases are failing because  sai_sdk_dump folder is not present in dump file

**Steps to reproduce the issue:**
1. Run show tech support test case

**Describe the results you received:**
"stderr": "ls: cannot access '/tmp/sonic_dump_str-marvell-acs-1_20230220_080014/sai_sdk_dump/': No such file or directory"

**Describe the results you expected:**
sai_sdk_dump folder is expected only for nvidia platform. This is platform specific change

Image:-
202005

**Comment by yxieca** [comment] 2023-02-22 16:40
Suggest check HLD if this folder sai_sdk_dump should always exists. If yes, then Marvell should fix the dump procedure. Otherwise, we should relax the check.

Nvidia will triage this issue further first.

**Comment by StormLiangMS** [comment] 2023-02-24 02:09
@roy-sror any progress update for this issue?

**Comment by roy-sror** [comment] 2023-02-26 07:56
@ppikh  is handling it. We'll keep you posted.

**Comment by ppikh** [comment] 2023-03-03 15:59
Hi @yxieca - do we have any HLD for techsupport?
I am not able to find it in: https://github.com/sonic-net/SONiC/tree/master/doc

**Comment by Blueve** [comment] 2023-08-16 14:28
@yxieca @ppikh since we don't have HLD for this, can we relax the sai_sdk_dump to Mellanox asic only?

**Comment by yxieca** [comment] 2023-08-16 17:00
> @yxieca @ppikh since we don't have HLD for this, can we relax the sai_sdk_dump to Mellanox asic only?

We can relax the check on Marvell platform. but why limit it to only Mellanox platform?

**Comment by Blueve** [comment] 2023-08-16 23:59
> > @yxieca @ppikh since we don't have HLD for this, can we relax the sai_sdk_dump to Mellanox asic only?
> 
> We can relax the check on Marvell platform. but why limit it to only Mellanox platform?

@yxieca I actually observe this error on Arista platform as well. If there is not a standard, then we shouldn't enforce it.

**Comment by Blueve** [comment] 2023-08-17 04:54
@yxieca I found that below code states that the sai_sdk_dump is only available for Nvidia(Mellanox) devices.

https://github.com/sonic-net/sonic-mgmt/blame/9b1cdee55bbadfc47a54df0ec501869cace17652/tests/common/plugins/conditional_mark/tests_mark_conditions.yaml#L988C4-L988C4

I believe that the issue here was introduced by https://github.com/sonic-net/sonic-mgmt/pull/7366 unexpected

**Comment by Blueve** [comment] 2023-08-18 05:03
@ppikh can you update the test case to check sai_sdk_dump for Mellanox device only?

**Comment by bingwang-ms** [comment] 2023-08-23 22:38
The test case should have been skipped on non Mellanox platform by PR https://github.com/sonic-net/sonic-mgmt/pull/7465.
Is the issue still there?

**Comment by bingwang-ms** [comment] 2023-08-23 22:46
The issue is caused by PR https://github.com/sonic-net/sonic-mgmt/pull/7366.
The function `validate_dump_file_content` need to be modified to check `sai_sdk_dump` only on Mellanox platform.

@volodymyrsamotiy @ppikh  Can you please check and fix?

**Comment by roy-sror** [comment] 2023-08-26 19:41
@Roman ***@***.***>- can you take care of this?

Thanks,
Roy
________________________________

**Comment by bingwang-ms** [comment] 2023-08-31 17:12
@roy-sror @ppikh @volodymyrsamotiy  Can you please prioritize on this issue? It's blocking the tech_support test on other platforms. Thanks!

**Comment by roy-sror** [comment] 2023-09-03 08:21
@SavchukRomanLv - please prioritize.

**Comment by bingwang-ms** [comment] 2023-09-05 16:02
Fixed by #9830

**Closed by bingwang-ms** 2023-09-05 16:02 UTC
Labels: Triaged
