### ISSUE TITLE
[202205][202305][ACL]Default Control Plane ACL RULE not added by acl-loader

### ISSUE THREAD

**Issue by richardyu-ms** [sonic-net/sonic-mgmt#10426] opened 2023-10-24 06:53 UTC
# **Description**
During development on ACL-related features, there are some questions about updating the ACL rule by using acl-loader.

For updating Acl rules (just focus on control rules here), we use the ``acl-loader`` with parameters ``full`` and ``table_name``, then expect one table-related rule updating. 
However, the behavior between different OS versions is inconsistent, with the same command.
The default DROP RULES appear in **SOME** versions.

- The sample ACL RULE update command is:
``sudo acl-loader update full  ./acl.json  --table_name [ACL_TABLE_NAME]``

> Note: For the data ``acl.json`` used in this question, they do not include the ``default acl rule``.

## Take 20220531.27 for example:
- After the update, DROP ACL RULES **NOT** appear
```
XXXXX@str-sXXXX-acs-1X:~$ show acl rule | grep DROP | wc
      0       0       0
XXXXX@str-sXXXX-acs-1X:~$ show acl rule | grep ACCEPT | wc     
    172    1204   14620
XXXXX@str-sXXXX-acs-1X:~$
```
In IPTABLES, the default drop rule for each protocol are also not added
```
XXXXX@str-sXXXX-acs-1X:~$ sudo iptables -L | grep -e "DROP.*[tcp|udp]"
DROP       all  --  anywhere             str-sXXXX-acs-1X.XXX.XXX
...
DROP       all  --  anywhere             anywhere
```
> New findings: The last one, the wildcard rule for all the traffic are added.

## In comparison with version 20191130.89
- After the update
```
XXXXX@STG02-XXXX-XXXX-16T1:~$  show acl rule | grep DROP | wc
      5      30     345
```
IPTABLES
```
 sudo iptables -L | grep -e "DROP.*[tcp|udp]"
DROP       tcp  --  anywhere             anywhere             tcp dpt:xxx
DROP       tcp  --  anywhere             anywhere             tcp dpt:xxxxx
DROP       tcp  --  anywhere             anywhere             tcp dpt:xxxx
DROP       udp  --  anywhere             anywhere             udp dpt:xxxx
...
DROP       all  --  anywhere             anywhere
```
> New findings: The last one, the wildcard rule for all the traffic are the same.

## Checked OS versions
**None default ACL rule(control plane)**
- 20220531: 27, 34, 35, 36, 43
- 20230531: 04

**Have default ACL rule(control plane)**
- 20181131: 51, 77, 90, 99, 101, 105, 108
- 20191130: 68, 70, 78, 83, 84, 86, 100, 107, 112
- 20201231: 67, 76, 81, 82,88, 89, 91, 95

**Steps to reproduce the issue:**
1. update ACL RULEs with command ``sudo acl-loader update full  ./acl.json  --table_name [ACL_TABLE_NAME]``
2. check acl rule ``show acl rule``
3. check iptables ``iptables -L``

**Describe the results you received:**
The behavior between different OS versions is inconsistent, with the same command.

**Describe the results you expected:**
The behavior between different OS versions should be the same, or some guide for different commands on different versions.
For the data ``acl.json`` used in this question, they do not include the ``default acl rule``.
The script, ``acl-loader`` should generate the ``DEFAULT rule`` automatically.

**Additional information you deem important:**

**Output of `show version`:**

```
     show ver
      
     SONiC Software Version: SONiC.20220531.27
     SONiC OS Version: 11
     Distribution: Debian 11.7
     Kernel: 5.10.0-18-2-amd64
     Build commit: 5e3b9620e9
     Build date: Mon May  8 20:39:33 UTC 2023
```

**Attach debug file `sudo generate_dump`:**

```
    (paste your output here)
```

**Comment by richardyu-ms** [comment] 2023-10-26 09:41
After further investigation, looks like this issue is not at risk.

Even the deny ACL rule does not appear in the ACL RULEs(with show ACL rule), one IPTABLE rule for deny all the traffic has been added.
               _DROP       all  --  anywhere             anywhere_

Then, un-accepted traffic will be dropped by iptables.

Verified this behavior on 202205.27 and 202305.06.
Also checked by loading a config_db.json without any deny rule, the `deny all` will be added in iptables and ip6tables.

**Comment by bingwang-ms** [comment] 2023-11-01 06:16
@richardyu-ms Can we close this issue? Any other concern?

**Comment by lizhijianrd** [comment] 2023-11-03 15:18
@bingwang-ms @richardyu-ms Since we have confirmed the default deny rule exists in `iptable`, I'll close this issue.

**Closed by lizhijianrd** 2023-11-03 15:18 UTC
